/*
 * This file is generated by jOOQ.
*/
package codingchallenge.database.tables.records;


import codingchallenge.database.tables.MyList;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MyListRecord extends UpdatableRecordImpl<MyListRecord> implements Record4<Integer, String, String, Date> {

    private static final long serialVersionUID = 540973935;

    /**
     * Setter for <code>public.my_list.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.my_list.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.my_list.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.my_list.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.my_list.statement</code>.
     */
    public void setStatement(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.my_list.statement</code>.
     */
    public String getStatement() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.my_list.creation_date</code>.
     */
    public void setCreationDate(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.my_list.creation_date</code>.
     */
    public Date getCreationDate() {
        return (Date) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Date> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Date> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MyList.MY_LIST.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MyList.MY_LIST.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MyList.MY_LIST.STATEMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return MyList.MY_LIST.CREATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getStatement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component4() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStatement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyListRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyListRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyListRecord value3(String value) {
        setStatement(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyListRecord value4(Date value) {
        setCreationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyListRecord values(Integer value1, String value2, String value3, Date value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MyListRecord
     */
    public MyListRecord() {
        super(MyList.MY_LIST);
    }

    /**
     * Create a detached, initialised MyListRecord
     */
    public MyListRecord(Integer id, String name, String statement, Date creationDate) {
        super(MyList.MY_LIST);

        set(0, id);
        set(1, name);
        set(2, statement);
        set(3, creationDate);
    }
}
