/*
 * This file is generated by jOOQ.
*/
package codingchallenge.database;


import codingchallenge.database.tables.ArchivedList;
import codingchallenge.database.tables.MyList;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ARCHIVED_LIST_PK = Indexes0.ARCHIVED_LIST_PK;
    public static final Index MY_LIST_PKEY = Indexes0.MY_LIST_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ARCHIVED_LIST_PK = Internal.createIndex("archived_list_pk", ArchivedList.ARCHIVED_LIST, new OrderField[] { ArchivedList.ARCHIVED_LIST.ID }, true);
        public static Index MY_LIST_PKEY = Internal.createIndex("my_list_pkey", MyList.MY_LIST, new OrderField[] { MyList.MY_LIST.ID }, true);
    }
}
