/*
 * This file is generated by jOOQ.
*/
package codingchallenge.database;


import codingchallenge.database.tables.ArchivedList;
import codingchallenge.database.tables.MyList;
import codingchallenge.database.tables.records.ArchivedListRecord;
import codingchallenge.database.tables.records.MyListRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ArchivedListRecord, Integer> IDENTITY_ARCHIVED_LIST = Identities0.IDENTITY_ARCHIVED_LIST;
    public static final Identity<MyListRecord, Integer> IDENTITY_MY_LIST = Identities0.IDENTITY_MY_LIST;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ArchivedListRecord> ARCHIVED_LIST_PK = UniqueKeys0.ARCHIVED_LIST_PK;
    public static final UniqueKey<MyListRecord> MY_LIST_PKEY = UniqueKeys0.MY_LIST_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ArchivedListRecord, Integer> IDENTITY_ARCHIVED_LIST = Internal.createIdentity(ArchivedList.ARCHIVED_LIST, ArchivedList.ARCHIVED_LIST.ID);
        public static Identity<MyListRecord, Integer> IDENTITY_MY_LIST = Internal.createIdentity(MyList.MY_LIST, MyList.MY_LIST.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ArchivedListRecord> ARCHIVED_LIST_PK = Internal.createUniqueKey(ArchivedList.ARCHIVED_LIST, "archived_list_pk", ArchivedList.ARCHIVED_LIST.ID);
        public static final UniqueKey<MyListRecord> MY_LIST_PKEY = Internal.createUniqueKey(MyList.MY_LIST, "my_list_pkey", MyList.MY_LIST.ID);
    }
}
