/*
 * This file is generated by jOOQ.
*/
package codingchallenge.database;


import codingchallenge.database.tables.MyList;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.my_list</code>.
     */
    public static final MyList MY_LIST = codingchallenge.database.tables.MyList.MY_LIST;
}
